# Generated by Django 3.2.5 on 2021-08-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='video_id',
        ),
    ]
