# Generated by Django 3.2.12 on 2022-02-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('learner_level', models.CharField(max_length=10)),
                ('points', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('portrait_url', models.CharField(max_length=200)),
            ],
        ),
    ]
