# Generated by Django 3.2.12 on 2022-04-06 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime(2022, 4, 6, 19, 31, 42, 446981))),
            ],
            options={
                'verbose_name': '2. 邮箱验证码',
                'verbose_name_plural': '2. 邮箱验证码',
            },
        ),
    ]
