# Generated by Django 3.2.5 on 2021-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_cover', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('video_author', models.CharField(max_length=40)),
                ('video_description', models.CharField(max_length=400)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
